package helper

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
)

type AzureOpenAIRequest struct {
	Messages []AzureMessage `json:"messages"`
}

type AzureMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type AzureOpenAIResponse struct {
	Choices []AzureChoice `json:"choices"`
	Error   *AzureError   `json:"error,omitempty"`
}

type AzureChoice struct {
	Message AzureMessage `json:"message"`
}

type AzureError struct {
	Message string `json:"message"`
	Code    string `json:"code"`
}

func PromptAzureOpenAI(prompt string) (string, error) {
	endpoint := os.Getenv("AZURE_OPENAI_ENDPOINT")
	apiKey := os.Getenv("AZURE_OPENAI_API_KEY")

	if endpoint == "" || apiKey == "" {
		return "", fmt.Errorf("AZURE_OPENAI_ENDPOINT or AZURE_OPENAI_API_KEY not configured")
	}

	reqBody := AzureOpenAIRequest{
		Messages: []AzureMessage{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request: %w", err)
	}

	req, err := http.NewRequest("POST", endpoint, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("api-key", apiKey)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to call Azure OpenAI API: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("azure OpenAI API returned status %d: %s", resp.StatusCode, string(body))
	}

	var azureResp AzureOpenAIResponse
	if err := json.Unmarshal(body, &azureResp); err != nil {
		return "", fmt.Errorf("failed to parse response: %w", err)
	}

	if azureResp.Error != nil {
		return "", fmt.Errorf("azure OpenAI API error: %s", azureResp.Error.Message)
	}

	if len(azureResp.Choices) == 0 {
		return "", fmt.Errorf("no response generated by Azure OpenAI")
	}

	return azureResp.Choices[0].Message.Content, nil
}

func AnalyzePictureWithAzureOpenAI(imageFile []byte, prompt string) (string, error) {
	return "", fmt.Errorf("vision analysis with Azure OpenAI not yet implemented")
}
